export { TrajectoryRecorder } from './trajectory'
export type { TrajectoryEntry, CompressionResult } from '@shared/types'
export { PatternDetector } from './pattern-detector'
export type { DetectedPattern, Suggestion } from './pattern-detector'
export { WriterModelUpdater } from './writer-model'
export type { WriterProfile, NextAction } from './writer-model'
export { SkillEvolver } from './skill-evolver'
export type { EvolvedShortcut } from './skill-evolver'
export { LearningEngine } from './engine'
export type { LearningAnalysis } from './engine'
